name: Java @ Publish
description: '[Composite] Publish a Java artifact to repository'

inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'
  java-distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'
  repsy-username:
    description: 'Repsy repository username'
    required: true
  repsy-password:
    description: 'Repsy repository password/token'
    required: true
  repsy-repo-name:
    description: 'Your Repsy repository name'
    required: true
  working-directory:
    description: 'Working directory where the publish should run'
    required: false
    default: '.'
  custom-publish-arguments:
    description: 'Additional arguments for the publish command'
    required: false
    default: ''
  artifact-name:
    description: 'Name of the artifact to publish'
    required: false
    default: 'java-artifact'
  artifact-path:
    description: 'Path to the artifact to publish'
    required: false
    default: 'target/*.jar'
  cache-enabled:
    description: 'Whether to use Maven dependency caching'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:

    - name: Set up JDK ${{ inputs.java-version }} (${{ inputs.java-distribution }})
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.cache-enabled == 'true' && 'maven' || '' }}
        server-id: repsy
        server-username: REPSY_USERNAME
        server-password: REPSY_PASSWORD

    - name: Verify POM Configuration
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if grep -q "<distributionManagement>" pom.xml; then
          echo "Distribution management already configured in pom.xml"
        else
          echo "Warning: You need to add distributionManagement section to your pom.xml"
          echo "Sample configuration for Repsy:"
          echo "<distributionManagement>"
          echo "  <repository>"
          echo "    <id>repsy</id>"
          echo "    <name>Repsy Maven Repository</name>"
          echo "    <url>https://repo.repsy.io/mvn/${{ inputs.repsy-username }}/${{ inputs.repsy-repo-name }}</url>"
          echo "  </repository>"
          echo "</distributionManagement>"
          exit 1
        fi

#    - name: Configure Maven settings
#      shell: bash
#      working-directory: ${{ inputs.working-directory }}
#      run: |
#        mkdir -p ~/.m2
#        cat > ~/.m2/settings.xml << EOF
#        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
#          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
#          <servers>
#            <server>
#              <id>repsy</id>
#              <username>${{ inputs.repsy-username }}</username>
#              <password>${{ inputs.repsy-password }}</password>
#            </server>
#          </servers>
#        </settings>
#        EOF
#
#        echo "Created settings.xml with proper credentials"

#    - name: Debug Maven settings
#      shell: bash
#      run: |
#        echo "Checking if settings.xml exists:"
#        ls -la ~/.m2/ || echo "No .m2 directory found"
#        if [ -f ~/.m2/settings.xml ]; then
#          echo "settings.xml structure (redacted):"
#          grep -v password ~/.m2/settings.xml
#        else
#          echo "No settings.xml found"
#        fi

    - name: Publish to Repsy Maven Repository
      shell: bash
      env:
        REPSY_USERNAME: ${{ inputs.repsy-username }}
        REPSY_PASSWORD: ${{ inputs.repsy-password }}
      run: mvn deploy

    - name: Upload artifact to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.working-directory }}/${{ inputs.artifact-path }}
        retention-days: 1