name: Java CI Workflow

on:
  workflow_call:
    inputs:
      fetch-depth:
        description: 'Number of commits to fetch'
        default: '1'
        required: false
        type: string
      lfs:
        description: 'Download Git-LFS files'
        default: 'false'
        required: false
        type: string
      submodules:
        description: 'Checkout submodules'
        default: 'false'
        required: false
        type: string
      java-version:
        description: 'Java version'
        default: '17'
        required: false
        type: string
      java-distribution:
        description: 'Java distribution'
        default: 'temurin'
        required: false
        type: string
      build-command:
        description: 'Build command'
        default: 'mvn -B clean compile'
        required: false
        type: string
      custom-build-arguments:
        description: 'Additional arguments for the build command'
        required: false
        default: ''
        type: string
      test-command:
        description: 'Test command to execute'
        required: false
        default: 'mvn -B test'
        type: string
      integration-test-command:
        description: 'Integration test command to execute'
        required: false
        default: 'mvn -B verify -DskipUnitTests'
        type: string
      custom-test-arguments:
        description: 'Additional arguments for the test command'
        required: false
        default: ''
        type: string
      skip-integration-tests:
        description: 'Whether to skip integration tests'
        required: false
        default: 'false'
        type: string
      coverage-enabled:
        description: 'Whether to collect code coverage metrics'
        required: false
        default: 'true'
        type: string
      test-results-path:
        description: 'Path where test results are stored'
        required: false
        default: 'target/surefire-reports'
        type: string
      coverage-report-path:
        description: 'Path where coverage reports are stored'
        required: false
        default: 'target/site/jacoco'
        type: string
      cache-enabled:
        description: 'Whether to use Maven dependency caching'
        default: 'false'
        required: false
        type: string
      working-directory:
        description: 'Working directory where the build should run'
        default: '.'
        required: false
        type: string
      maven-settings-path:
        description: 'Path to maven settings.xml file'
        default: 'maven-settings.xml'
        required: false
        type: string


jobs:
  build:
    name: Build Java Project
    runs-on: ubuntu-latest

    outputs:
      build-cache-key: ${{ steps.cache-key.outputs.key }}

    steps:
      - name: Checkout Repository
        uses: euthiagodealmeida/conveyor-actions/.github/actions/shared/checkout@develop
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
          lfs: ${{ inputs.lfs }}
          submodules: ${{ inputs.submodules }}

      - name: Generate Cache Key
        id: cache-key
        shell: bash
        run: |
          echo "key=build-${{ github.sha }}-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Build Project
        uses: euthiagodealmeida/conveyor-actions/.github/actions/java/build@develop
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          build-command: ${{ inputs.build-command }}
          custom-build-arguments: ${{ inputs.custom-build-arguments }}
          cache-enabled: ${{ inputs.cache-enabled }}
          working-directory: ${{ inputs.working-directory }}
          maven-settings-path: ${{ inputs.maven-settings-path }}

      - name: Cache Target Directory
        uses: actions/cache/save@v3
        with:
          path: ${{ inputs.working-directory }}/target
          key: ${{ steps.cache-key.outputs.key }}

  test:
    name: Test Java Project
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: euthiagodealmeida/conveyor-actions/.github/actions/shared/checkout@develop
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
          lfs: ${{ inputs.lfs }}
          submodules: ${{ inputs.submodules }}

      - name: Restore Target Directory
        uses: actions/cache/restore@v3
        with:
          path: ${{ inputs.working-directory }}/target
          key: ${{ needs.build.outputs.build-cache-key }}
          fail-on-cache-miss: true

      - name: Test Project
        uses: euthiagodealmeida/conveyor-actions/.github/actions/java/test@develop
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          test-command: ${{ inputs.test-command }}
          integration-test-command: ${{ inputs.integration-test-command }}
          custom-test-arguments: ${{ inputs.custom-test-arguments }}
          skip-integration-tests: ${{ inputs.skip-integration-tests }}
          coverage-enabled: ${{ inputs.coverage-enabled }}
          working-directory: ${{ inputs.working-directory }}
          test-results-path: ${{ inputs.test-results-path }}
          coverage-report-path: ${{ inputs.coverage-report-path }}
          maven-settings-path: ${{ inputs.maven-settings-path }}